---
title: Extracting tree parameters from UAV lidar data.
author:
- affiliation: CIRGEO Interdepartmental Research Center of Research of Geomatics
  corresponding: francesco.pirotti@unipd.it
  email: francesco.pirotti@unipd.it
  footnote: 1
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
- affiliation: TESAF Department
  email: francesco.pirotti@unipd.it
  footnote: 2
  name: Francesco Pirotti
  orcid: 0000-0002-4796-6406
date: "`r Sys.Date()`"
address:
  - code: Some Institute of Technology
    address: Department, Street, City, State, Zip
  - code: Another University
    address: Department, Street, City, State, Zip
footnote:
  - code: 1
    text: "Corresponding Author"
  - code: 2
    text: "Equal contribution"
abstract: |
  This is the abstract.

  It consists of two paragraphs.

journal: "An awesome journal" 
bibliography: mybibfile.bib
#linenumbers: true
#numbersections: true
csl: elsevier-harvard.csl
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


Introduction
==========================

#### Installation

Laser scanner data are becoming increasingly available and with larger volume. 

This is due to market-driven improvement of technology, making sensors lighter and more accurate.

Terrestrial laser scanners (TLS) provide faster and more dense scans. Productivity has also increased due to light batteries and lighter sensors. Both factors allow more scans per day, thus surveying areas with a denser point cloud. 

For some years now laser scanners are deployed on remotely piloted aircraft systems (RPAS), sometimes referred to as unmanned airborne vehicles (UAVs) or simply "drones". Normal aircrafts require a minimum relative flight height (RFH), usually arount 150 m above terrain. RFH is  lower for RPAS, depending on the national regulations, allowing a much denser point cloud. 

For the reasons stated above, it is not uncommon for post-processing to deal with very dense point clouds and larger volumes of data.

Forestry has greatly benefitted from laser scanning technology, thanks to laser's ability to go "behind" foliage. This is possible due to gaps in the canopy, that allow laser signals to be only partially reflected and partially pass through to reach other objects "behind" the first. This is often referred to as "penetration" capability of laser scanners in canopies. When scanning vegetation cover from above, this allows a few laser signals to be reflected by the terrain surface. Having samples of the positions of points on the terrain surface is fundamental to estimate a digital terrain model (DTM), that is required for several other models. Hydrological modelling requires accurate DTM, as well as forest modelling uses the DTM and DSM to extract the normalized DSM (nDSM). The latter is also known as canopy height model (CHM) when only vegetation covers the area.

Forest management fundamentally requires the spatial distribution of trees and information on their specites, height, diameter, volume and biomass. In the case of point clouds from laser scanning, the height can be measured with significant accuracy, depending on the density of points at bottom (DTM) and on the top of the canopy (DSM), in particular the tree apex.

In the case of TLS, tree diameter can also be measured and the tree branch structure can be extracted by segmentation []. When laser scanning is done from aerial supports, such as RPAS or normal aircrafts, the height of the tree is more easily extracted. 

As mentioned, new technologies allow for much denser datasets, in particular from RPAS: The high density dataset from aerial laser scanning becomes more similar to the common density of TLS scans. Of course the two tecnologies provide a different distribution of point density, due to the scan geometry.

Fast and streamlined methods for extracting information from dense point clouds is a topic worth investigating. 


 
Materials and method
===================

The work uses a voxel-based density distribution to initiate tree detection and successive segmentation and parameter definition.
n octree structure and 

The Point Cloud Library (PCL) [@Rusu2011] is used for point cloud analysis, and the LASZip library [@Isenburg2013] is used for reading LAS [@Loskot2008] and compressed LAZ  formats.

Octrees are used to organize space. The supervoxel element is used from [@Papon2013]

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
